pachd:
  resources:
    requests:
      cpu: 1000m
      memory: 2048M
    limits:
      cpu: 1000m
      memory: 2048M

etcd:
  resources:
    requests:
      cpu: 250m
      memory: 512M
    limits:
      cpu: 250m
      memory: 512M
