pachd:
    resources:
        requests:
            cpu: 4000m
            memory: 12Gi
        limits:
            cpu: 4000m
            memory: 12Gi
    nodeSelector:
        loadtest: enabled

etcd:
    resources:
        requests:
            cpu: 1000m
            memory: 1000M
        limits:
            cpu: 1000m
            memory: 1000M
    nodeSelector:
        loadtest: enabled
