pachd:
    resources:
        requests:
            cpu: 1000m
            memory: 6Gi
        limits:
            cpu: 1000m
            memory: 6Gi

etcd:
    resources:
        requests:
            cpu: 250m
            memory: 512M
        limits:
            cpu: 250m
            memory: 512M
